-- AlterTable
ALTER TABLE "Service" ADD COLUMN     "govtFee" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "otherCost" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Work" ADD COLUMN     "serviceCost" DOUBLE PRECISION NOT NULL DEFAULT 0;
